# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "f2fs";
    options = [
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc,gc_merge"
      "lazytime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/WKBOOT";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/EXTRA" =
  { device = "/dev/disk/by-label/EXTRA";
    fsType = "f2fs";
    options = [
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc,gc_merge"
      "lazytime"
    ];
  };

  fileSystems."/mnt/nvRAID" = {
    device = "/dev/disk/by-label/nvRAID";
    neededForBoot = true;
    fsType = "f2fs";
    options = [
      "compress_algorithm=zstd:6"
      "compress_chksum"
      "atgc,gc_merge"
      "lazytime"
    ];
  };

  fileSystems."/nix" = {
    depends = [
      "/"
      "/mnt/nvRAID"
    ];
    device = "/mnt/nvRAID/nix";
    neededForBoot = true;
    fsType = "none";
    options = [
      "bind"
#        "ro"
    ];
  };


  fileSystems."/mnt/RAID" =
  { device = "/dev/disk/by-label/SSDRAID";
    fsType = "ext4";
  };
}
